name: ubuntu

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Run ansible
        run: ansible-playbook -c=local -i local, base.yml
