name: vagrant-up

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  vagrant-up:
    runs-on: macos-12
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: |
            ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
